### PR TITLE
Updated with support of PubSub+ 9.4 and later

### PR DESCRIPTION
**Pull request by bczoma**
*Issue #, if available:*

*Description of changes:*
- Updated with support of PubSub+ 9.4 and later

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bczoma** [comment]
@davmayd  - Hey Dave, sorry to bug you: you seem to have contributed to this branch most recently back in April. Would you know who can approve this PR and merge `develop` to `master` ? `master` is broken now if using recent versions of the Solace Event Broker without these changes. Thanks a lot in advance: Balazs

**Comment by vsnyc** [comment]
Hi Balazs

I’ll take care of it today. Sorry for the delay.

Vinod

**Comment by bczoma** [comment]
Hi Vinod, nice to hear from you 😊

No worries, thanks a lot!

Balazs

**Comment by vsnyc** [comment]
Hi Balazs, good to hear from you as well. This is taken care of. I did have to add a couple of commits (https://github.com/aws-quickstart/quickstart-solace-pubsub/commit/e111e33b1be1b1a1f893e478cfdea3e724a3e550, https://github.com/aws-quickstart/quickstart-solace-pubsub/commit/0bc6c40c78b10dcf50e1014d8ca26b83703c852c) to make it pass our testing. Please sync your fork.

**Pull request merged**
